### ISSUE TITLE
Remover a máscara do campo referência

### ISSUE THREAD

**Issue by mlrmelo** [bitts/PagTesouro#10]
O campo Referência é um campo opcional com até 20 posições **numéricas**.
Está com máscara "mm/aaaa", como se fosse relativo a um mês/ano, mas é simplesmente um código numérico

**Comment by bitts** [comment]
Alterado para... onde é permitido somente números e de forma não obrigatória (uso do 9 / 0 para obrigatório)
```
$('#input_referencia').mask('9#');
```
