### ISSUE TITLE
Centralizar campo CPF

### ISSUE THREAD

**Issue by mlrmelo** [bitts/PagTesouro#11]
Apenas estética...
Como está, parece que a página está mal formatada (dá a impressão que o campo nome não coube no espaço e foi jogado pra baixo)

**Comment by bitts** [comment]
![Screenshot_20210412_104147](https://user-images.githubusercontent.com/1100489/114404321-fa722780-9b7b-11eb-9585-5c5db9e4dc1d.png)

**Comment by mlrmelo** [comment]
Show!!! Ficou muito bom...
