### ISSUE TITLE
Alterar apontamento do formulário

### ISSUE THREAD

**Issue by mlrmelo** [bitts/PagTesouro#13]
Da maneira como está, a chamada ao formulário é feita através da administração do Joomla (**`/?option=com_pagtesouro`**).
O ideal é que possa ser feita a chamada através de um apelido (Ex: **/pagtesouro**), como qualquer artigo ou módulo do Joomla. Isto, inclusive faz parte das questões de segurança (usar resescrita de URL e URLs aigáveis).
Aqui no 2º CTA, adotamos uma maneira simples, mas eficaz de proteger a administração: temos 2 URL para a página:
- admin.<OM>.eb.mil.br → acessível **apenas na EBNet**, onde se pode acessar a pasta **/administrator**
- www.<OM>.eb.mil.br → acessível **na Internet**, onde **NÃO** se pode acessar a pasta **/administrator**
São 2 VirtualHost no apache, onde o **www** aponta para uma subpasta que contém apenas links para TUDO que está na pasta principal **EXCETO** a pasta **/administrator**.
Da maneira como está, ele faz a chamada para a pasta **/administrator/componentes/com_pagtesouro**, então ele não encontra o formulário na internet e traz a página em branco
Esta é uma condição essencial para que possa ser adotado como padrão de uso pelo 2º CTA (provavelmente, o mesmo aconteça nos outros CT/CTA)
**Uma sugestão:**
Normalmente, os componentes criam uma entrada na lista de "tipos de ítens de menu", que faze a carga do formulário correspondente.
Ou, se for mais fácil, criar um apontamento direto para o formulário, usando o alias (apelido) dele.

**Comment by bitts** [comment]
Opa confuso esse Joomla, vamos lá... na verdade eu é que não entendi como resolver o problema:

`Uma sugestão: Normalmente, os componentes criam uma entrada na lista de "tipos de ítens de menu", que faze a carga do formulário correspondente.`
Como isso pode ajudar no sistema? não entendi como modificar os códigos, ou mesmo onde é necessário modificar para sanar este problema.

`Ou, se for mais fácil, criar um apontamento direto para o formulário, usando o alias (apelido) dele.`
O que for mais viável ou tiver que sofrer menos modificações no código, melhor! =D

**Comment by bitts** [comment]
Acredito que a melhor maneira de resolver o problema seja através da criação de uma duplicata do arquivo `pagtesouso.json` (onde contém as configurações cadastradas pelo usuário de tokens e serviços). Ou a criação de um link simbolico para tal arquivo:
```
public function createLinktoConfig(){
        $target = "/images/pagtesouro/";
        if(!is_dir($target)){
            $target = "../images/pagtesouro/";
            $link = getcwd();
            $tar = explode('/',$link);
            unset($tar[count($tar)-1]);
            unset($tar[count($tar)-1]);
            $tar = implode('/',$tar);
            if(!is_dir("{$tar}/images/pagtesouro/")){
                mkdir("{$tar}/images/pagtesouro/", 0777);
            }
            $target = $tar . "/images/pagtesouro/";
            $link = getcwd()."/";

            $path = "arquivos/";
            $diretorio = dir($link);

            while( $arquivo = $diretorio->read() ){
                if( !in_array($arquivo, Array('.','..') )){
                        if($arquivo === "pagtesouro.json")
                            @link("{$link}{$arquivo}", "{$target}{$arquivo}");
                }
            }
            $diretorio->close();
        }
    }
```

**Comment by bitts** [comment]
Adicionada
