### ISSUE TITLE
Erro ao recuperar o arquivo JSON

### ISSUE THREAD

**Issue by mlrmelo** [bitts/PagTesouro#14]
Ao fazer uma recuperação do Arquivo JSON backupeado, ele **apaga** os Tokens e códigos de serviço existentes, mas mantém o CodUG e o nome OM, acrescentando, ao final, o que foi restaurado.
Assim, ficam as OMs, sem códigos **MAIS** o que foi restaurado...
Quando tem que instalar uma versão nova, ele **apaga** os dados que existem e coloca os códigos de exemplo.
Ao recuperar o JSON, vai ficar:
- Os exemplos +
- O recuperado
Obrigando o usuário a apagar o exemplo

**Comment by bitts** [comment]
Este problema ocorre por que o sistema não recupera o arquivo diretamente...
Na verdade ele abre o conteúdo do arquivo e joga ele no formulário através da ação:
```
reader.onload = function() {
    let json = reader.result;
    $('textarea.pagtesourojson').val(json);
    populate_pagtesouro(json);
    URL.revokeObjectURL(reader);
}
```

Onde **populate_pagtesouro(json);** é responsável por popular o formulário principal com os dados do arquivo.
Só após essa ação, que o usuário escolhe salvar ou não os dados no arquivo **pagtesouro.json**, acontece que ele não remove os dados já preenchidos anteriormente (no caso logo que se instala o componente tem dados preenchidos do modelo).

O correto seria remover o conteudo existente e após isso importar o arquivo.

O que posso fazer é limpar todos os dados (preenchidos ou não) no formulário, após isso importar o arquivo.

```
reader.onload = function() {
    let json = reader.result;
    $('textarea.pagtesourojson').val(json);

    $('fieldset.fielduge').remove(); //<--- remove aqui todos dados já cadastrados

    populate_pagtesouro(json);
    URL.revokeObjectURL(reader);
}
```

**Comment by bitts** [comment]
Necessário validar.

**Comment by mlrmelo** [comment]
Funcionou!!!
Maravilha!!!
